version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=sample
    volumes:
      - $PWD/db/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
