version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=sample
    volumes:
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
